# Generated by Django 4.2.11 on 2024-04-18 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('performance_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
                ('performance_time', models.CharField(max_length=50)),
                ('age_requirement', models.CharField(max_length=50)),
                ('performance_type', models.CharField(choices=[('MUSICAL', '뮤지컬'), ('DRAMA', '연극')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_num', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('user_id', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('date', models.CharField(max_length=50)),
                ('likes_count', models.IntegerField()),
                ('view_count', models.IntegerField()),
                ('performance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.performance')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('VISUAL', '시각화'), ('POSTER', '포스터')], max_length=50)),
                ('image', models.ImageField(default='default_visual.png', upload_to='visual/')),
                ('performance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.performance')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.performance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
