# Generated by Django 4.2.11 on 2024-04-16 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('store_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_num', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('performance_time', models.DateTimeField()),
                ('age_requirement', models.IntegerField()),
                ('performance_type', models.CharField(max_length=50)),
                ('image_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_num', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('user_id', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('date', models.DateField()),
                ('likes_count', models.IntegerField()),
                ('view_count', models.IntegerField()),
                ('performance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.performance')),
            ],
        ),
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.AddField(
            model_name='file',
            name='performance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.performance'),
        ),
    ]
