# Generated by Django 4.2.11 on 2024-04-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_file_performance_review_delete_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='age_requirement',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='performance',
            name='end_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='performance',
            name='performance_num',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='performance',
            name='performance_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='performance',
            name='start_date',
            field=models.CharField(max_length=50),
        ),
    ]
