# Generated by Django 4.2.11 on 2024-04-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_alter_performance_age_requirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='image',
            field=models.ImageField(default='default.png', upload_to='poster/'),
        ),
    ]
