# Generated by Django 4.2.11 on 2024-04-16 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_performance_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='image_path',
        ),
    ]
