# Generated by Django 4.2.11 on 2024-04-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0005_remove_performance_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='image',
        ),
        migrations.AlterField(
            model_name='review',
            name='review_num',
            field=models.CharField(max_length=50),
        ),
    ]
