# Generated by Django 4.2.11 on 2024-04-18 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performance', '0006_remove_performance_image_alter_review_review_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='store_path',
        ),
        migrations.AddField(
            model_name='file',
            name='image',
            field=models.ImageField(default='default.png', upload_to='poster/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title', to=settings.AUTH_USER_MODEL)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.performance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
