# Generated by Django 4.2.11 on 2024-04-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0006_remove_performance_image_alter_review_review_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='store_path',
        ),
        migrations.AddField(
            model_name='file',
            name='image',
            field=models.ImageField(default='default_visual.png', upload_to='visual/'),
        ),
        migrations.AddField(
            model_name='performance',
            name='image',
            field=models.ImageField(default='default.png', upload_to='poster/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_num',
            field=models.IntegerField(),
        ),
    ]
