# Generated by Django 4.2.11 on 2024-04-18 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performance', '0007_remove_file_store_path_file_image_alter_review_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='owner',
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
