# Generated by Django 4.2.11 on 2024-04-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=50)),
                ('location_text', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('perform_time', models.DateTimeField()),
                ('perform_type', models.CharField(max_length=50)),
            ],
        ),
    ]
